### ISSUE TITLE
Major Bug in E4

### ISSUE THREAD

**Issue by ProfNemo409** [pkLucid/Pokemon-Lucid#1]
![Wall bug](https://github.com/pkLucid/Pokemon-Lucid/assets/173475980/c076b477-a47f-4cca-b6dc-ca58e5666654)
Major Bug in E4. I didnt know where the E4 are and who is there. I went into one of the one, to quickly see who is there. Re-went into the battle and the door closes on me.

**Comment by ProfNemo409** [comment]
Small Update. I just tested it, this happens with all E4 doors.
edit: I can 100% reoccur this bug. Unfortunately my save is bricked now as I cant enter this E4 member. 
If you need further information, you could also contact me on discord: Captinnmo @pkLucid

**Comment by pkLucid** [comment]
> Small Update. I just tested it, this happens with all E4 doors. edit: I can 100% reoccur this bug. Unfortunately my save is bricked now as I cant enter this E4 member. If you need further information, you could also contact me on discord: Captinnmo @pkLucid

@ProfNemo409 What version are you using?

**Comment by ProfNemo409** [comment]
When it happened, I used I think it was 1.1? Not the current one, but I believe the one before. I luckily had a backup file and could finish my Nuzlocke, so I didnt try it with a newer patch. It was 100% recreateable on the patch I played though.

**Comment by pkLucid** [comment]
> When it happened, I used I think it was 1.1? Not the current one, but I believe the one before. I luckily had a backup file and could finish my Nuzlocke, so I didnt try it with a newer patch. It was 100% recreateable on the patch I played though.

Thx. I'll try to find the issue.

**Comment by pkLucid** [comment]
@ProfNemo409 thanks, I finally was able to solve it since I got a save from someone who had the same issue. it is fixed in the 1.2.2 release
